### ISSUE TITLE
RuntimeError: optimizeBlockSize: NVCC failed

### ISSUE THREAD

**Issue by BarryLiu97** [BrainsOnBoard/procedural_paper#10]
Hi, I was trying to run the tutorial https://github.com/neworderofjamie/new_genn_tutorials/blob/master/tutorial1/tutorial1.py, and encountered this error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/PCL/my_test/test1.py", line 26, in <module>
    model.build()
  File "e:\pcl\procedural_paper\genn\pygenn\genn_model.py", line 506, in build
    backend = self._backend_module.create_backend(self._model, output_path, self.backend_log_level, preferences);
  File "e:\pcl\procedural_paper\genn\pygenn\genn_wrapper\CUDABackend.py", line 134, in create_backend
    return _CUDABackend.create_backend(model, outputPath, backendLevel, preferences)
RuntimeError: optimizeBlockSize: NVCC failed
```
IDLE：pycharm
system: Windows 10 
python: 3.7.10
pygenn:  0.4.3
CUDA info
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by neworderofjamie** [comment]
This isn't actually very well explained in the documentation but, I think, the issue here is that you need to _use_ PyGeNN in the same environment you built it in with both Visual Studio **and** Anaconda active. I've never used PyCharm before but I imagine you can launch it from a command prompt or batch file which sets this up.

**Comment by BarryLiu97** [comment]
Actually, I ran the .py file from the terminal, the VS Code, and Pycharm, and they all have the same error as described above.  As to the environment, ```import pygenn``` works fine.
The error in VS Code and terminal is
```
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Traceback (most recent call last):
  File "test1.py", line 26, in <module>
    model.build()
  File "e:\pcl\procedural_paper\genn\pygenn\genn_model.py", line 506, in build
    backend = self._backend_module.create_backend(self._model, output_path, self.backend_log_level, preferences);
  File "e:\pcl\procedural_paper\genn\pygenn\genn_wrapper\CUDABackend.py", line 134, in create_backend
    return _CUDABackend.create_backend(model, outputPath, backendLevel, preferences)
RuntimeError: optimizeBlockSize: NVCC failed
```

**Comment by neworderofjamie** [comment]
Sorry I wasn't clear - I didn't mean the _Python_ environment, I mean the environment variables etc you get when you start a "x64 Native Tools Command Prompt" from the Visual Studio start menu (which presumably you used to build PyGeNN). You need to have these set when you _use_ GeNN as well.

**Comment by BarryLiu97** [comment]
Oh, that, yes, I didn't use "x64 Native Tools Command Prompt" from the Visual Studio start menu, I used MSBuild Command Prompt, OK I'll try!

**Comment by neworderofjamie** [comment]
If you use the [new windows terminal](https://github.com/microsoft/terminal) (I can highly recommend it), you can add an entry to the settings file which lets you easily create new terminals with both Anaconda and the Visual Studio stuff already activated:

```json
{
     "guid": "{c38950e4-5b5e-40fe-8153-279b8f297397}",
     "name": "Developer command prompt",
     "commandline": "cmd.exe /K \"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat\" & \"C:\\Users\\jamie\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\activate.bat\" \"C:\\Users\\jamie\\AppData\\Local\\Continuum\\anaconda3\"\"",
     "startingDirectory": "%USERPROFILE%",
     "hidden": false
},
```

**Comment by BarryLiu97** [comment]
OK, the code works now. Thank you! And yes, the new Windows Terminal is much prettier, thank you so much!

**Comment by BarryLiu97** [comment]
Hi, I have a question. How do I debug my code if I can only run it from the Prompt? If I set a breakpoint in VS.

**Comment by neworderofjamie** [comment]
You _should_ be able to launch your IDE from that command prompt and everything _should_ work

**Comment by BarryLiu97** [comment]
Oh, YES! Thank you, I didn't know that I can do this.
