### ISSUE TITLE
ValueError of np.load()

### ISSUE THREAD

**Issue by BarryLiu97** [BrainsOnBoard/procedural_paper#13]
Hi
I was running [plot_multi_area.py](https://github.com/BrainsOnBoard/procedural_paper/blob/master/scripts/plot_multi_area.py) after running  [calc_multi_area_stats.py](https://github.com/BrainsOnBoard/procedural_paper/blob/master/scripts/calc_multi_area_stats.py), 
and the error below happens [here](https://github.com/BrainsOnBoard/procedural_paper/blob/master/scripts/plot_multi_area.py#L66)
```
Traceback (most recent call last):
  File "plot_multi_area.py", line 197, in <module>
    excitatory_actor, inhibitory_actor = plot_area("V1", v1_1_0_axis, "chi_1_0")
  File "plot_multi_area.py", line 67, in plot_area
    data = np.load(s)
  File "/home/lz/anaconda3/envs/pcl/lib/python3.7/site-packages/numpy/lib/npyio.py", line 445, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
The Numpy version I used is 1.16.2 1.19.2 1.20.0, and I load the npy file in ```chi_1_0/genn_recorings``` like ```V1_5E.npy``` separately, the error was the same.

**Comment by neworderofjamie** [comment]
Can you tell me how large the files in ``chi_1_0/genn_recordings`` are? The only way I can see this happening is if the calc_multi_area_stats.py script isn't able to find the simulation output

**Comment by neworderofjamie** [comment]
I _suspect_ the problem is this data is stored using [Git LFS](https://git-lfs.github.com/) so you need to ensure that you have that installed before checking out this repository

**Comment by BarryLiu97** [comment]
Hi
    Sorry, I've been caught up in something recently and didn't follow up. The size of the chi_1_0/genn_recordings is 3.5 KB.

**Comment by neworderofjamie** [comment]
In that case, definitely try checking it out with git lfs

**Comment by BarryLiu97** [comment]
You are right! I'll close the issue now.
